### ISSUE TITLE
ValueSortedDict occasionally enters error state

### ISSUE THREAD

**Issue by diwenshi61** [grantjenks/python-sortedcollections#18]
Occasionally, the ValueSortedDict throws errors when attempting to delete an element in it.
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...", line 1325, in ...
    ...
  File "/home/.../.local/lib/python3.8/site-packages/sortedcollections/recipes.py", line 162, in __delitem__
    self._list_remove(key)
  File "/home/.../.local/lib/python3.8/site-packages/sortedcontainers/sortedlist.py", line 2041, in remove
    raise ValueError('{0!r} not in list'.format(value))
ValueError: '44586356890' not in list
```
At that moment, this is the ValueSortedDict:
```
ValueSortedDict(<function ... at 0x7efc81945b80>, {'44586356890': {...}, '44586093075': {...}})
```
It appears that for whatever reason, one of the keys is dropped from the list of keys but the item remains in the dict.
This happens somewhat rarely, and I'm not sure what causes it.
Clearing the dict appears to be a viable solution.

**Comment by grantjenks** [comment]
What operations do you perform on the sorted dict? Seems like one of them is getting the sorted list and dictionary out of sync. That’s likely a bug or oversight on my part.

**Comment by diwenshi61** [comment]
Nothing special, just creating the dict, adding single items to the dict, deleting from the dict, clearing the dict, and peekitem. Using Ubuntu 20.04, Python version 3.8.5, sortedcollections 2.1.0, sortedcontainers 2.3.0. The asyncio library is also used and the dict is modified in different asyncio tasks, but this shouldn't impact it.

**Comment by grantjenks** [comment]
I added some stress tests in PR #19 but it passes without error. You'll have to provide more details about the operations and data types involved.

**Comment by diwenshi61** [comment]
Unfortunately, I can't really provide any source code as it is proprietary. I don't think I'll spend time chasing it down as it's very rare and can be resolved by catching the exception and manually deleting the item through clearing the dict and readding all the other items. Thanks for the help!
