### ISSUE TITLE
Performance issue - bulk updates to a ValueSortedDict

### ISSUE THREAD

**Issue by pushshift** [grantjenks/python-sortedcollections#20]
I have some code that looks something like this:
```
    for hashtag in sortedKeyList:
        hashtag_text = hashtag[1]
        if hashtag_text in SortedHashtagDict:
            SortedHashtagDict[hashtag_text] += 1
        else:
            SortedHashtagDict[hashtag_text] = 1
```

My guess is that each time a value is modified in a ValueSortedDict, the dict sorts itself. Is there a method to increment values in bulk and then perform some sort of resort after updating many keys? Is this the correct way to use this or am I missing a feature?

Thanks!

**Comment by grantjenks** [comment]
It doesn’t sort all the values but it does need to balance internal data structures.

There’s an update() method that does changes in bulk. Since the tally operation doesn’t care about order, use collections.Counter and then pass the counts into update()
