### ISSUE TITLE
Need a help on this error

### ISSUE THREAD

**Issue by DanaIdeisan** [grantjenks/python-sortedcollections#21]
xin= []
next_x= []

for i in range(window, len(Train)):
    xin.append(Train[i-window:i])
    next_x.append(Train[i])
    
xin, next_x= np.array(xin), np.array(next_x)

______________________________________________________________

KeyError                                  Traceback (most recent call last)
~\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2894             try:
-> 2895                 return self._engine.get_loc(casted_key)
   2896             except KeyError as err:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 10

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-26-162c78065743> in <module>
      4 for i in range(window, len(Train)):
      5     xin.append(Train[i-window:i])
----> 6     next_x.append(Train[i])
      7 
      8 xin, next_x= np.array(xin), np.array(next_x)

~\anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2900             if self.columns.nlevels > 1:
   2901                 return self._getitem_multilevel(key)
-> 2902             indexer = self.columns.get_loc(key)
   2903             if is_integer(indexer):
   2904                 indexer = [indexer]

~\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2895                 return self._engine.get_loc(casted_key)
   2896             except KeyError as err:
-> 2897                 raise KeyError(key) from err
   2898 
   2899         if tolerance is not None:

KeyError: 10

**Comment by grantjenks** [comment]
Doesn’t look like you’re using sorted collections. Maybe you meant to ask in Pandas repo?

**Comment by DanaIdeisan** [comment]
What is Pandas repo? do I have to install it? 

This is what I run before:

#Set window of past points for LSTM model

window=10

#split 80/20 into train/test data

Train=df[:-100]
Test=df[-100-window:]
print(Train)
print(Test)
