### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by wumpus** [grantjenks/python-sortedcollections#3]
I see that you already fixed these in sortedcontainers on 9/3...

/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/sortedcollections/recipes.py:174: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class OrderedSet(co.MutableSet, co.Sequence):
/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/sortedcollections/ordereddict.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class KeysView(co.KeysView, co.Sequence):
/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/sortedcollections/ordereddict.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class ItemsView(co.ItemsView, co.Sequence):
/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/sortedcollections/ordereddict.py:48: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class ValuesView(co.ValuesView, co.Sequence):

**Comment by grantjenks** [comment]
Fixed and deployed at v1.1.1
