### ISSUE TITLE
KeyError: '10'

### ISSUE THREAD

**Issue by Schneckenfuss** [grantjenks/python-sortedcollections#7]
Why is that? Did I make a mistake?

```
sorted = ValueSortedDict()

for i in range(0, 250):
    sorted.update({str(i): randint(100, 150000)})
```

**Result**

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    sorted.update({str(i): randint(100, 150000)})
  File "/usr/local/lib/python3.5/dist-packages/sortedcontainers/sorteddict.py", line 563, in update
    self._setitem(key, pairs[key])
  File "/usr/local/lib/python3.5/dist-packages/sortedcontainers/sorteddict.py", line 306, in __setitem__
    self._list_add(key)
  File "/usr/local/lib/python3.5/dist-packages/sortedcontainers/sortedlist.py", line 1783, in add
    key = self._key(value)
  File "/usr/local/lib/python3.5/dist-packages/sortedcollections/recipes.py", line 147, in key_func
    return self[key]
KeyError: '10'
```

**Versions**

sortedcollections (1.1.1)
sortedcontainers (2.1.0)

**Comment by grantjenks** [comment]
That's a bug. Good find! Fixed at 7f434be and deployed to PyPI in version 1.1.2

For faster and more idiomatic code, I would write your example as:

```
sorted = ValueSortedDict()

for i in range(0, 250):
    sorted[str(i)] = randint(100, 150000)
```

That avoids the dictionary temporary which is being created repeatedly. It also works in version 1.1.1.

Thank you for the bug report.

**Comment by Schneckenfuss** [comment]
Thanks for your fast response and fix, I really appreciate that Sir!

**Comment by dionisboss** [comment]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-5c5468cf79e2> in <module>
      4 your_unit = str(input("Type unit you want to check:")).capitalize()
      5 unit_lvl =0
----> 6 user.unit_prob(your_unit,unit_lvl)

<ipython-input-3-403d703be6f5> in unit_prob(self, your_unit, units_level)
     44             print("Did not understand that")
     45         #get the problist for my level
---> 46         my_prob_list= levels_and_prob[self.mylvl]
     47 
     48         #getunit level

KeyError: 10

**Comment by grantjenks** [comment]
@dionisboss your stack trace does not provide enough information for me to reproduce the possible bug. As far as I can tell the code simply needs the key, value pair initialized before indexing.
