### ISSUE TITLE
ValueSortedDict() with descending order (reversed)

### ISSUE THREAD

**Issue by Kaulkwappe** [grantjenks/python-sortedcollections#8]
Is that easily possible without performance issues? A parameter would be nice :)

And thanks again for your work! This library is really great.

**Comment by grantjenks** [comment]
There's no easy way to reverse the order in the ValueSortedDict itself. Accessing the end of the dictionary should just as fast as accessing the start. Is there an API that gives access to one end but not the other?

Of course, if you're using numbers as values then you can just negate them.

**Comment by Kaulkwappe** [comment]
Good evening Sir,

thanks for your fast answer!

Okay, I thought you could allow it from beginning on. I use it for 60 x 2,000-180,000 records at the moment and that seems to generally be the best solution in terms of performance.

I indeed use numbers as values. Negating them was a _brilliant_ idea, I tested it and it looks good so far. In my case, it does not add any overhead too.

**Comment by grantjenks** [comment]
Your welcome!
